services:
  dind:
    image: docker:20-dind
    restart: always
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: ""
    command:
      - --storage-driver=overlay2
    volumes:
      - dind-docker-data:/var/lib/docker

  runner:
    restart: always
    image: registry.gitlab.com/gitlab-org/gitlab-runner:alpine
    configs:
      - source: gitlab-runner-config
        target: /etc/gitlab-runner/config.toml
    volumes:
      - runner-cache:/cache
      ###- /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=tcp://dind:2375

configs:
  gitlab-runner-config:
    file: ./config/config.toml

volumes:
  dind-docker-data:
    driver: local
  runner-cache:
    driver: local
