services:
  dind:
    image: docker:20-dind
    restart: always
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: ""
    command:
      - --storage-driver=overlay2
    volumes:
      - dind-docker-data:/var/lib/docker

  runner:
    restart: always
    image: registry.gitlab.com/gitlab-org/gitlab-runner:alpine
    volumes:
      - runner-config:/etc/gitlab-runner:z
      - runner-cache:/cache
      ###- /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=tcp://dind:2375

volumes:
  dind-docker-data:
    driver: local
  runner-config:
    driver: local
  runner-cache:
    driver: local
