concurrent = 1
check_interval = 0
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

# Add your runner configuration here after registration
# [[runners]]
#   name = "my-runner"
#   url = "https://gitlab.com/"
#   token = "YOUR_RUNNER_TOKEN"
#   executor = "docker"
#   [runners.docker]
#     tls_verify = false
#     image = "alpine:latest"
#     privileged = false
#     disable_entrypoint_overwrite = false
#     oom_kill_disable = false
#     disable_cache = false
#     volumes = ["/cache"]
#     shm_size = 0
